### ISSUE TITLE
Missing Data in SQLite Database v 3.0.32

### ISSUE THREAD

**Issue by Batman1703** [uktrade/tariff-data-manual#16]
Hi,

I raised a support ticket on the data.gov.uk regarding missing data but they have asked me to contact the Publisher. There are no publisher details on the "Tariffs to trade with the UK from Jan 2021" link published by the DTI (https://www.data.gov.uk/dataset/3bee9a8a-e69c-400e-add5-3345a87a8e25/tariffs-to-trade-with-the-uk-from-1-january-2021) so I am hoping that the publishers of the User Manual are also the publishers of the dataset. If now please can you point me in the correct direction to address the following:

In the SQLite database there is table called Additional_Code_Types. This is missing some additional codes types such as V (VAT) and X (Excise). As a consequence of this, (but may be more deaper) there are approximately 47,000 measures that are missing from the Measures table that of AddittionalCodeType V, the most of these have an AdditionalCode of VATZ like for Commodity Codes descriping products for Children's Clothing. Likewise there are also all of the Excise measure types 471, 473 etc Additional Code Type X471, X473... that are also missing. The linking table between the Additional_Code_Types and Measure_Types is also missing.

Data analysed: v3.0.32  23rd July 2022.

The following is a list of MeasureTypes with no Measures.

Measure Type	      CountofMeasures
Amount of levy	0
Common Veterinary Entry Document (CVED)	0
Dump Undertakings	0
**Excises	0**
Export refund (ingredients - amounts)	0
Import control of timber and timber products subject to the FLEGT licensing scheme-Cameroon	0
Import control of timber and timber products subject to the FLEGT licensing scheme-Central Africa Republic	0
Import control of timber and timber products subject to the FLEGT licensing scheme-Ghana	0
Import control of timber and timber products subject to the FLEGT licensing scheme-Republic of Congo	0
MOB+MCM	0
Outward processing post. surveillance	0
Posterior export surveillance	0
Suplementary amount	0
**Value added tax	0**

CVED, Excise and VAT are important for our HMRC CDS development.

I would be grateful if youcould look at this please.

Thanks

Paul

**Comment by simonwo** [comment]
Hi Paul, thanks for getting in touch. 

If you have questions about the contents of the file, you can contact tariffimplementation@trade.gov.uk which will put you in touch with the team that maintains the Tariff in DIT.

The DIT-provided Tariff file doesn't currently include VAT or Excise, as these are HMRC-specific controls (and hence we don't have the data currently). The only place to get these at the moment is from the CDS download or via the [Trade Tariff API](https://api.trade-tariff.service.gov.uk/#gov-uk-trade-tariff-api). I will have a think about if we could grab and provide these when publishing the open tariff file though.

All of those other measure types are ones I would expect to be empty. The FLEGT country-specific ones will have been replaced by a general purpose FLEGT measure, and the surveillance measures are now defunct in the UK. I would expect CVED to be present in some form, but I think it might be replaced by [CHED documentation](https://www.trade-tariff.service.gov.uk/certificate_search?description=CHED) which will appear as specific certificates. I would encourage you to use the above email to ask that question if that results are not what you'd expect.

Thanks,
Simon
